DATA:
  data_name: s3dis
  data_root: dataset/s3dis/trainval_fullarea
  test_area: 5
  classes: 13
  fea_dim: 6
  voxel_size: 0.04
  voxel_max: 80000
  loop: 30

TRAIN:
  arch: lgpa
  use_xyz: True
  sync_bn: False
  ignore_label: 255
  train_gpu: [0]
  workers: 16
  batch_size: 4
  batch_size_val: 2
  base_lr: 0.0005
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.01
  drop_rate: 0.5
  manual_seed: 7777
  print_freq: 1
  save_freq: 1
  save_path: exp/s3dis
  weight: 
  resume: exp/s3dis/model/model_last.pth 
  evaluate: True 
  eval_freq: 1
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path: exp/s3dis/model/model_best.pth 
  save_folder: exp/s3dis/test
  names_path: dataset/s3dis/s3dis_names.txt
