DATA:
  data_name: shapenet
  data_root: dataset/shapenet
  classes: 50
  fea_dim: 6
  voxel_size:
  voxel_max:
  loop: 6

TRAIN:
  arch: lgpa
  use_xyz: True
  sync_bn: False
  ignore_label: -100
  train_gpu: [0]
  workers: 16
  batch_size: 16
  batch_size_val: 1
  base_lr: 0.003
  epochs: 400
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.01
  drop_rate: 0.5
  manual_seed: 7777
  print_freq: 1
  save_freq: 1
  save_path: exp/shapenet
  weight:
  resume: exp/shapenet/model/model_last.pth 
  evaluate: True
  eval_freq: 1
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_list:
  test_list_full:
  split: val
  test_gpu: [0]
  test_workers: 16
  batch_size_test: 1
  model_path: exp/shapenet/model/model_best.pth 
  save_folder: exp/shapenet/test
  names_path:
